[theme]
primaryColor = "#6B46C1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF5F7"
textColor = "#1F2937"
font = "sans serif"

[theme.dark]
primaryColor = "#6B46C1"
backgroundColor = "#1A1A1F"
secondaryBackgroundColor = "#2D2D3D"
textColor = "#FFFFFF" 